### ISSUE TITLE
Puppet Forge Availability

### ISSUE THREAD

**Issue by genebean** [stschulte/puppet-rpmkey#1]
Any chance you'd release this on the Puppet Forge?

**Comment by stschulte** [comment]
I haven't created an account yet and certainly have to learn a bit about creating proper metadata but I'll look into it. Shouldn't be to hard I guess. Thanks for input anymay

**Comment by genebean** [comment]
If you are interested, I am happy to write up a metadata.json for you.

**Comment by stschulte** [comment]
Thanks for your offer, I played with `puppet module generate` so I guess I have a sensible metdata file now. I will look at the module building part on the weekend most probably.

**Comment by genebean** [comment]
That's awesome, thanks for taking the time.

**Comment by stschulte** [comment]
@genebean The module is now available on the forge https://forge.puppetlabs.com/stschulte/rpmkey
I'm still struggling with `puppet module build` a bit because I thought this would also create metadata about the custom types (like available parameters and their documentation) but I did not got that part to work.

**Comment by genebean** [comment]
thanks @stschulte!

**Comment by stschulte** [comment]
@genebean Thanks for your suggestion, I hope it will reach more users there. BTW: Can you let me now on which operatingsystem you used the module? I updated the metadata with operatingsystem support for RHEL5 and RHEL6 because these are the only systems where I run this myself but I suppose it will work on basically every rpm based distribution.

**Comment by genebean** [comment]
I have used it on both CentOS and RHEL 7.
