### ISSUE TITLE
Key Does Not Install

### ISSUE THREAD

**Issue by rlkeeney** [stschulte/puppet-rpmkey#9]
I'm new to puppet so it's very possiblem that I am doing something wrong.

I installed it using this command:

puppet module install stschulte-rpmkey

I have it in a module I created. It runs without errors but the key doesn't get installed. I've been poking around at this for two days and not getting anywhere.

**Comment by stschulte** [comment]
The module itself does not install anything it just gives you the `rpmkey` resource that you can use in another manifest. Can you please share your actual puppet manifest?

If you say it runs without error, does this mean puppet will not print any message or do you always get the message that puppet claims the keys has been installed?

Otherwise what does `puppet resource rpmkey` on a random puppet agent gives you? It should list what the `rpmkey` thinks are the currently installed keys.

**Comment by rlkeeney** [comment]
Puppet doesn't print any messages. Nothing in the log or on the screen. From what you have told me so far it seems like I'm missing something. I only have a server and one client.

**I'm running the client in the forground like this:**

[root@rapidroy ~]# puppet agent --server=puppetmaster.fldoi.gov --no-daemonize --verbose
notice: Starting Puppet client version 2.7.26
info: Caching catalog for rapidroy.dfs.state.fl.us
info: Applying configuration version '1475173900'
notice: Finished catalog run in 0.65 seconds

**On the server:**

[root@puppetmaster manifests]# puppet resource rpmkey
rpmkey { '0608B895':
  ensure => 'present',
}
rpmkey { '2FA658E0':
  ensure => 'present',
}
rpmkey { '4BD6EC30':
  ensure => 'present',
}
rpmkey { 'FD431D51':
  ensure => 'present',
}

**On the client**

[root@rapidroy ~]# puppet resource rpmkey
Could not run: Could not find type rpmkey

**The manifest:** 

[root@puppetmaster manifests]# cat nodes.pp
node 'rapidroy.dfs.state.fl.us' {
    include linux-base
}

[root@puppetmaster manifests]# cat nodes.pp
node 'rapidroy.dfs.state.fl.us' {
    include linux-base
}

[root@puppetmaster manifests]# pwd
/etc/puppet/modules/linux-base/manifests
[root@puppetmaster manifests]# cat init.pp
class linux-base {

  package { "mc":
    ensure => present,
  }

  package { "vim-enhanced":
    ensure => present,
  }

  package { "mutt":
    ensure => present,
  }

  package { "logwatch":
    ensure => present,
  }

  package { "firefox":
    ensure => present,
  }

  package { "net-snmp":
    ensure => present,
  }

  service { "snmpd":
    ensure  => "running",
    enable  => true,
    require => Package["net-snmp"]
  }

  package { "net-snmp-utils":
    ensure => present,
  }

  package { "policycoreutils-python":
    ensure => present,
  }

  package { "rsyslog":
    ensure => present,
  }

   service { "rsyslog":
    ensure  => "running",
    enable  => true,
    require => Package["rsyslog"]
  }

  file { "/etc/snmp/snmpd.conf":
    notify  => Service['snmpd'],
    ensure  => present,
    owner   => "root",
    group   => "root",
    mode    => "0600",
    source  => "puppet://$puppetserver/modules/linux-base/snmpd.conf",
    }

  file { "/etc/rsyslog.conf":
    notify  => Service['rsyslog'],
    ensure  => present,
    owner   => "root",
    group   => "root",
    mode    => "0644",
    source  => "puppet://$puppetserver/modules/linux-base/rsyslog.conf",
    }

   file { "/root/.bashrc":
    ensure  => present,
    owner   => "root",
    group   => "root",
    mode    => "0644",
    source  => "puppet://$puppetserver/modules/linux-base/root-bashrc",
    }

   rpmkey { "4c881cbf":
     ensure => present,
     source => "https://packages.vmware.com/tools/keys/VMWARE-PACKAGING-GPG-DSA-KEY.pub"
   }

  }

**Comment by stschulte** [comment]
make sure your catalog is working (are the `packages` resources working for example?). You are showing the contents of the `node.pp` file but what really is evaluated for node definitions is `site.pp` (which can include something like `import node.pp`).

Also it looks like pluginsync is not working (otherwise the `rpmkey` type would be known on the agent). This can be because the module is not installed to the correct path, or because [pluginsync](https://docs.puppet.com/puppet/latest/reference/configuration.html#pluginsync) is not enabled in the agents configuration. It looks like you are using a relativly old puppet version, where the default was to not pluginsync (this [changed](https://projects.puppetlabs.com/issues/5521) for puppet >=3 and was later deprecated alltogether).

If you are starting new I can only suggest to use a more recent puppet version. With versions before 3 you will probably run into issues with certain modules from the forge and puppet 4 introduces so many changes that you may want to start with that one to save yourself from upgrade issues in the future.

**Comment by rlkeeney** [comment]
It was the pluginsync. Set it to true and everything worked.  I looked at this before and since the documentation I looked at said true was the default so I didn't look any more. looks like the version has already caused me problems.

**Comment by rlkeeney** [comment]
Thanks for the help.
